### ISSUE TITLE
install google fonts

### ISSUE THREAD

**Issue by renejuan** [wch/extrafont#70]
I recently saw the package [sysfonts](https://cran.r-project.org/web/packages/sysfonts/sysfonts.pdf). It occurred to me that it will be a great addition to download/install Google Fonts using the extrafont package. Google Fonts seems to have an API. Not too familiar with the API and how/where sysfonts package download the fonts. If possible I will be happy to look at this a little more and add some functions. Will this be something of interest?

**Comment by wch** [comment]
Sounds useful, but I think it would make more sense to have a separate package that does this.

**Comment by renejuan** [comment]
After looking at that package a little more I agree. I think the author make his package available to install fonts only for other of his packages but it probably can be modified without much problem to make fonts available to Windows and other packages including `extrafont`. I will suggest some changes to the author of `sysfonts`.
