### ISSUE TITLE
object 'windowsFonts' of mode 'function' was not found (blogdown)

### ISSUE THREAD

**Issue by mark-druffel** [wch/extrafont#83]
I added loadfonts to my project .Rprofile and got an error saying no function The functions work in blogdown, but not in .Rprofile. I realized after opening the ticket that this is because grDevices does not load before .Rprofile (I think). Below is the error.

``` r
library(extrafont)
loadfonts("win", quiet = F)

Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'windowsFonts' of mode 'function' was not found
Calls: <Anonymous> -> match.fun -> get
Execution halted
```

I was able to fix it with the code below. Closing the issue.
``` r
library(grDevices)
library(extrafont)
loadfonts("win", quiet = F)

Registering fonts with R
```

**Comment by LiXingguangBrandonStark** [comment]
how to install the font of "Young"?

**Comment by LiXingguangBrandonStark** [comment]
library(grDevices)
> library(extrafont)
> loadfonts("win", quiet = F)
Error in windowsFonts() : could not find function "windowsFonts"

**Comment by LiXingguangBrandonStark** [comment]
i am using Mac.
